% Create a spiralArchimedean antenna
% Generated by MATLAB(R) 24.1 and Antenna Toolbox 24.1
%Generated on:01-Apr-2024 13:18:51

%% Antenna Properties 

antennaObject = design(spiralArchimedean, 13.56*1e6);
antennaObject.NumArms = 1;
antennaObject.Turns = 6;
antennaObject.InnerRadius = 0.0175;
antennaObject.OuterRadius = 0.0205;
antennaObject.WindingDirection = 'CW';
antennaObject.Conductor.Name = 'Copper';
antennaObject.Conductor.Conductivity = 5.96*1e7;
antennaObject.Conductor.Thickness = 3.556e-05;
antennaObject.Load = lumpedElement(Impedance=1.17);

% Show
figure;
show(antennaObject) 

%% 3-D radiation pattern
p = PatternPlotOptions
p.SizeRatio = 1;
p.Transparency = 0.5;
pattern(antennaObject,1.356e7,patternOptions=p)

%% S-parameters & Impedance Graphs
%resonantFrequency(antennaObject,10e6:1e6:100e6,Method="Sparameters");
%resonantFrequency(antennaObject,10e6:1e5:14e6,Method="Impedance");
